DynamicPrices/Controllers/DBController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;

namespace DynamicPrices.Controllers
{
    public class DBController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IProduseService _produseService;

        public DBController(IConfiguration configuration, IProduseService produseService)
        {
            _configuration = configuration;
            _produseService = produseService;
        }

        // GET: DBController
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Produse()
        {
            //lista de produse electronice (categoria)
            Dictionary<string, int> tipuriProduse = _produseService.GetTipProduseElectronice();

            return View(tipuriProduse);
        }

        public IActionResult Servicii()
        {
            return View();
        }

        public IActionResult ProduseElectronice(string tipProdus)
        {
            //lista de produse electronice dupa tip
            List<Dictionary<string, object>> produseDupaTip = _produseService.GetProduseDupaTip(tipProdus);

            return Json(produseDupaTip);
        }

        public IActionResult ListaDeProduse(string tipProdus)
        {
            //lista de produse electronice dupa tip
            Dictionary<int, string> produse = _produseService.GetProduseElectronice(tipProdus);
            var arrayProduse = produse.Select(p => new { id_produs = p.Key, nume_produs = p.Value }).ToArray(); 

            return Json(arrayProduse);
        }

        public IActionResult IstoriePreturiDupaProdus(int product_id)
        {
            //istoria preturilor dupa produs
            List<object> priceHistory = _produseService.GetPriceHistoryByProduct(product_id);

            return Json(priceHistory);
        }

        public IActionResult StocDupaProdus(int idProdus)
        {
            //stocul curent al unui produs
            int stoc = _produseService.GetStocActualDupaProdus(idProdus);

            return Ok(stoc);
        }

        public IActionResult PretDupaProdus(int idProdus)
        {
            //pretul curent al unui produs
            decimal pret = _produseService.GetPretCurentDupaProdus(idProdus);

            return Ok(pret);
        }

        public IActionResult MinMaxStoc(int idProdus)
        {
            List<int> listaStoc = _produseService.MinMaxStoc(idProdus);

            return Json(listaStoc);
        }
    }
}

DynamicPrices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dynamic Prices</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DynamicPrices.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary box-shadow mb-2">
            <!--bg-white_border-bottom-->
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Dynamic Pricing</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DB" asp-action="Produse">Produse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DB" asp-action="Servicii">Servicii</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Admin">Admin</a>
                        </li>
                    </ul>
                    <!--<partial name="_LoginPartial" />-->
                </div>
            </div>
        </nav>
    </header>
    <div class="container main-container">
        <main role="main" class="pb-3">
            @if (ViewBag.MenuAdmin ?? false)
            {
                <link rel="stylesheet" href="~/css/menuAdmin.css" />
                <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
                
                <div class="sidebar-btn bg-primary">
                    <span class="fas fa-bars"></span>
                </div>
                <nav class="sidebar bg-primary">
                    <div class="text">
                        Menu
                    </div>
                    <ul>
                        <li class="active"><a asp-controller="Admin" asp-action="Admin"><i class="bi bi-x-diamond"></i> Dashboard</a></li>
                        <li>
                            <a href="#" class="feat-btn">
                                <i class="bi bi-database"></i> Produse
                                <span class="fas fa-caret-down first"></span>
                            </a>
                            <ul class="feat-show">
                                <li><a asp-controller="Admin" asp-action="Electronice">Electronice</a></li>
                                <li><a href="#">Tip2</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="serv-btn">
                                <i class="bi bi-database"></i> Servicii
                                <span class="fas fa-caret-down second"></span>
                            </a>
                            <ul class="serv-show">
                                <li><a href="#">Publicitate</a></li>
                                <li><a href="#">Tip2</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="det-btn">
                                <i class="bi bi-file-text"></i> Detalii
                                <span class="fas fa-caret-down third"></span>
                            </a>
                            <ul class="det-show">
                                <li><a asp-controller="Admin" asp-action="Clienti">Clienți</a></li>
                                <li><a href="#">Vânzări Produse</a></li>
                                <li><a href="#">Vânzări Servicii</a></li>
                            </ul>
                        </li>
                        <li><a href="#">-/-/-</a></li>
                        <li><a href="#">-/-/-</a></li>
                    </ul>
                </nav>
                <script>
                    $('.sidebar-btn').click(function () {
                        $(this).toggleClass("click");
                        $('.sidebar').toggleClass("show");
                    });
                    $('.feat-btn').click(function () {
                        $('.sidebar ul .feat-show').toggleClass("show");
                        $('.sidebar ul .first').toggleClass("rotate");
                    });
                    $('.serv-btn').click(function () {
                        $('.sidebar ul .serv-show').toggleClass("show1");
                        $('.sidebar ul .second').toggleClass("rotate");
                    });
                    $('.det-btn').click(function () {
                        $('.sidebar ul .det-show').toggleClass("show2");
                        $('.sidebar ul .third').toggleClass("rotate");
                    });
                    $('.sidebar ul li').click(function () {
                        $(this).addClass("active").siblings().removeClass("active");
                    });
                </script>
            }
            @RenderBody()
        </main>
    </div>

    @if (ViewBag.ShowFooter == null || ViewBag.ShowFooter)
    {
        <footer class="footer bg-primary text-white">
            <div class="container">
                <i class="bi bi-bar-chart"></i> 2024 - Dynamic Pricing
            </div>
        </footer>
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>